"use strict";
(()=>{
  let token="",watchRevision="",guideDocument=null,guideDraft=null,idSequence=0;
  const $=id=>document.getElementById(id),message=(text,error=false)=>{$("message").textContent=text;$("message").classList.toggle("error",error)};
  function takeToken(){const params=new URLSearchParams(location.hash.slice(1)),value=params.get("token")||"";history.replaceState(null,"",location.pathname+location.search);return value}
  async function request(path,options={}){const headers={Authorization:`Bearer ${token}`,...(options.headers||{})},response=await fetch(path,{cache:"no-store",...options,headers}),payload=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok){const error=new Error(payload.error||`HTTP ${response.status}`);error.status=response.status;throw error}return payload}
  function renderWatchlist(payload){watchRevision=payload.revision;$("watchlist").replaceChildren(...payload.symbols.map(symbol=>{const li=document.createElement("li"),label=document.createElement("span"),button=document.createElement("button");label.textContent=symbol;button.type="button";button.className="danger";button.textContent="删除";button.onclick=()=>removeSymbol(symbol);li.append(label,button);return li}))}
  async function loadWatchlist(){renderWatchlist(await request("/api/watchlist"))}
  async function addSymbol(event){event.preventDefault();const symbol=$("symbol").value.trim();if(!symbol)return;try{renderWatchlist(await request("/api/watchlist",{method:"POST",headers:{"Content-Type":"application/json","If-Match":watchRevision},body:JSON.stringify({symbol})}));$("symbol").value="";message("自选股票已更新。") }catch(error){await conflict(error,"自选股票")}}
  async function removeSymbol(symbol){try{renderWatchlist(await request(`/api/watchlist/${encodeURIComponent(symbol)}`,{method:"DELETE",headers:{"Content-Type":"application/json","If-Match":watchRevision},body:"{}"}));message("自选股票已更新。") }catch(error){await conflict(error,"自选股票")}}
  function clone(value){return JSON.parse(JSON.stringify(value))}
  const nextId=prefix=>`${prefix}-${Date.now().toString(36)}-${(++idSequence).toString(36)}`;
  function renderGuide(){const root=$("guide");root.replaceChildren();guideDraft.sections.forEach((section,sectionIndex)=>{const box=document.createElement("section"),head=document.createElement("div"),title=document.createElement("input"),add=document.createElement("button"),remove=document.createElement("button");box.className="guide-section";head.className="section-head";title.value=section.title;title.setAttribute("aria-label","分类标题");title.oninput=()=>section.title=title.value;add.type=remove.type="button";add.textContent="添加条目";remove.textContent="删除分类";remove.className="danger";remove.disabled=guideDraft.sections.length===1;add.onclick=()=>{section.topics.push({id:nextId("topic"),title:"新条目",body:"请填写内容"});renderGuide()};remove.onclick=()=>{guideDraft.sections.splice(sectionIndex,1);renderGuide()};head.append(title,add,remove);box.appendChild(head);section.topics.forEach((topic,topicIndex)=>{const row=document.createElement("label"),input=document.createElement("input"),area=document.createElement("textarea"),deleteTopic=document.createElement("button");row.className="topic";row.append("条目标题");input.value=topic.title;area.value=topic.body;input.oninput=()=>topic.title=input.value;area.oninput=()=>topic.body=area.value;deleteTopic.type="button";deleteTopic.className="danger";deleteTopic.textContent="删除条目";deleteTopic.disabled=section.topics.length===1;deleteTopic.onclick=()=>{section.topics.splice(topicIndex,1);renderGuide()};row.append(input,area,deleteTopic);box.appendChild(row)});root.appendChild(box)})}
  async function loadGuide(){guideDocument=await request("/api/options-guide");guideDraft=clone(guideDocument);renderGuide();message("已读取最新版说明。")}
  async function saveGuide(){try{guideDocument=await request("/api/options-guide",{method:"PUT",headers:{"Content-Type":"application/json","If-Match":guideDocument.revision},body:JSON.stringify({sections:guideDraft.sections})});guideDraft=clone(guideDocument);renderGuide();message("说明已保存。") }catch(error){if(error.status===409){message("保存冲突：当前编辑文本已保留。请先复制需要保留的内容，再点“重新读取”获取最新版后合并。",true);return}message(`说明保存失败：${error.message}`,true)}}
  async function conflict(error,label){if(error.status===409){message(`${label}已被其他会话修改，正在重新读取；请再次操作。`,true);await loadWatchlist();return}message(`${label}更新失败：${error.message}`,true)}
  async function start(){token=takeToken();if(!token){message("管理会话令牌缺失，请关闭此页并重新启动本机管理工具。",true);return}try{const health=await request("/api/health");$("health").textContent=health.configured?"Alpaca 已配置":"Alpaca 待配置";await Promise.all([loadWatchlist(),loadGuide()])}catch(error){message(`管理会话验证失败：${error.message}`,true)}}
  $("addForm").onsubmit=addSymbol;$("addSection").onclick=()=>{if(!guideDraft)return;guideDraft.sections.push({id:nextId("section"),title:"新分类",topics:[{id:nextId("topic"),title:"新条目",body:"请填写内容"}]});renderGuide()};$("reloadGuide").onclick=loadGuide;$("saveGuide").onclick=saveGuide;start();
})();
